/**
 * Public types. Adding fields is non-breaking, renaming or removing needs a major bump
 */


// Configuration

export interface BotConfig {
    /**
     * Path to the .morokbot file from the web wizard. Read once at construction,
     * keys are imported into stateDir on first start and the file is not re-read after that
     */
    tokenFile?: string

    /**
     * Where Signal state lives: identity, sessions, prekeys, plus channel-key and group-secret state
     * Default ./bot-state/, holds private keys after import, so chmod 0700 it
     * Must be exclusive to one bot. Two processes on one stateDir corrupt each other's state,
     * the SDK takes a best-effort pid lock but give each bot its own directory
     */
    stateDir?: string

    /** Default https://app.morok.me. Override for self-host / dev */
    apiBaseUrl?: string

    /** Default derived from apiBaseUrl (http->ws, https->wss, +/ws) */
    wsUrl?: string

    /** Replenish OTPKs when count falls below this, default 100 */
    replenishThreshold?: number

    /** Target OTPK count after replenish, default 200, the server per call cap */
    replenishTarget?: number

    /** Background loop interval in ms, default 5 minutes. 0 disables it,
     *  which drains the prekey pool in production, so use only in tests */
    backgroundIntervalMs?: number

    /** Pino-shaped logger or anything with info/warn/error/debug. Default is silent */
    logger?: SdkLogger

    /**
     * If true, call backfillChannelKeys whenever a member joins a group/channel the bot is in,
     * so a new joiner can read history when the bot is the only online member
     * Off by default, backfill is expensive on convs with many devices and epochs
     * Safe to enable, the server filters by joined_secret_version so pre-join history can't leak
     */
    autoBackfillOnJoin?: boolean

    serveBackfillRequests?: boolean
}

export interface SdkLogger {
    info:  (obj: object, msg?: string) => void
    warn:  (obj: object, msg?: string) => void
    error: (obj: object, msg?: string) => void
    debug: (obj: object, msg?: string) => void
}


// .morokbot file shape, generated by the web wizard

export interface MorokbotKeyPair {
    pub:  string  // base64
    priv: string  // base64
}

export interface MorokbotSignedPreKey {
    keyId:     number
    pub:       string  // base64
    priv:      string  // base64
    signature: string  // base64, XEdDSA over pub by identity priv
}

export interface MorokbotOneTimePreKey {
    keyId: number
    pub:   string
    priv:  string
}

export interface MorokbotFile {
    version:           1
    botUserId:         number
    username:          string
    token:             string  // bot:<botUserId>:<secret>
    registrationId:    number
    identityKey:       MorokbotKeyPair
    /** Account-level cross-signing key. Optional for legacy wizards that pre-date it, new wizards always include it */
    accountSigningKey?: MorokbotKeyPair
    signedPreKey:      MorokbotSignedPreKey
    oneTimePreKeys:    MorokbotOneTimePreKey[]
}


// Events

/** A user. Resolved lazily on first mention and cached */
export interface Peer {
    userId:      number
    username:    string
    displayName: string | null
}

/** DIRECT = peer-to-bot DM, GROUP and CHANNEL = channel-key flows. Routes bot.reply to peer or conversation */
export type ConversationType = 'DIRECT' | 'GROUP' | 'CHANNEL'


export interface IncomingMessage {
    /** Persistent server id (messages.id) */
    messageId:       number
    conversationId:  number
    conversationType: ConversationType
    sender:          Peer
    senderDeviceId:  number
    /** Text body, or the caption that came with an attachment, empty string if none. Always a string */
    text:            string
    /** Single-attachment messages. undefined when the message is a gallery (see `gallery` below) or text-only */
    attachment?:     IncomingAttachment
    /** Multi-attachment bubble (2-10 items). Mutually exclusive with `attachment` */
    gallery?:        IncomingGallery
    /** Sender-stable id shared by every fan-out copy of one logical send. bot.reply threads it through
     *  so a reply targets the logical message across all device copies */
    clientMsgId:     string | null
    replyToId:       number | null
    threadRootId:    number | null
    createdAt:       Date
}

export interface CommandInvocation extends IncomingMessage {
    /** Command name without the leading slash */
    command:  string
    /** Everything after the command name, trimmed. Empty if none */
    args:     string
    /** args split on whitespace */
    argv:     string[]
}

export interface BotStartEvent {
    peer:      Peer
    startedAt: Date
}

export interface BotStopEvent {
    peer:      Peer
    stoppedAt: Date
}

/** Bot was added to a group or channel. By the time the handler fires the SDK has pulled the channel-key copies,
 *  so an immediate group_message decrypts */
export interface ConversationAddedEvent {
    conversationId:   number
    conversationType: 'GROUP' | 'CHANNEL'
    /** Title if the group has one, null otherwise */
    title:            string | null
    addedAt:          Date
}

/** Bot was removed. The SDK drops local state before the handler fires, no further messages decrypt unless re-added */
export interface ConversationKickedEvent {
    conversationId:   number
    /** 'kicked' = admin removed, 'left' = conversation destroyed */
    reason:           'kicked' | 'left'
    /** Admin who initiated, if known */
    actorUserId:      number | null
    removedAt:        Date
}

export interface ReactionEvent {
    /** Server id of the reactor's fan-out twin of the reacted-to message
     *  To find which message was reacted to, match clientMsgId below */
    messageId:    number
    /** Logical id shared by every fan-out copy of the reacted-to message,
     *  matching clientMsgId on IncomingMessage and SendResult. null on legacy rows without client_msg_id */
    clientMsgId:  string | null
    reactor:      Peer
    /** Decoded reaction content, any unicode string and not only an emoji
     *  The bot receives the reaction envelope and decrypts it like a message
     *  null on a removal or if a group reaction's channel-key has not reached the bot yet */
    unicode:      string | null
    /** false = reactor removed their previous reaction */
    added:        boolean
}

export interface DisconnectInfo {
    reason: 'transport' | 'auth' | 'shutdown'
    code?:  number | string
    /** false on shutdown, true otherwise (SDK will reconnect) */
    willReconnect: boolean
}


// REST wrappers

export interface BotCommand {
    command:     string  // lower-case, no leading slash
    description: string
    sortOrder:   number
}

export interface BotControl {
    id:       string
    label:    string
    icon?:    string
    command?: string
    children?: BotControl[]
}

export interface ControlEvent {
    controlId:        string
    sender:           Peer
    conversationId:   number
    conversationType: ConversationType
}


// Attachments

/**
 * Video note shape name, an open string passed to the receiver, which renders the names it knows
 * and shows circle for anything else. Plain string so a new receiver shape works without an SDK release
 *
 * Names the receiver renders: circle, square, slanted, pill, oval, arch, diamond, pentagon, gem, clamShell,
 * sunny, cookie1, cookie2, cookie3, cookie4, clover1, clover2, burst, softBurst, puffyDiamond, pixelCircle, heart
 */
export type VideoNoteShape = string

/** One attachment per send. Use SendArgs.attachments for galleries */
export type AttachmentInput =
    | {
        kind: 'file'
        /** Raw bytes. Buffer or Uint8Array */
        data: Buffer | Uint8Array
        /** Filename shown on the receiver's download UI */
        name: string
        /** Mime. Defaults to application/octet-stream */
        mime?: string
    }
    | {
        kind: 'voice'
        data: Buffer | Uint8Array
        /** Seconds. Receiver clamps to [0.1, 600] (10-min cap for voice notes) */
        duration: number
        /** Up to 64 ints in [0..100] */
        waveform?: number[]
        /** Defaults to audio/ogg */
        mime?: string
    }
    | {
        kind: 'video_note'
        data: Buffer | Uint8Array
        /** Seconds. Receiver clamps to [0.5, 300] (5-min cap for video notes) */
        duration: number
        /** Default 'circle' */
        shape?: VideoNoteShape
        /** Defaults to video/webm */
        mime?: string
    }


/**
 * Inbound attachment. download() is lazy, bytes hit the network only when called and return decrypted plaintext,
 * the server never had the key. mime is sender-supplied, treat it as a hint with no security guarantee
 */
export interface IncomingAttachment {
    kind:     'file' | 'voice' | 'video_note'
    fileId:   number
    sha256:   string
    /** Sender-supplied */
    mime:     string
    /** Plaintext size in bytes */
    size:     number
    /** Filename for 'file'. null for voice / video_note */
    name:     string | null
    /** Seconds, present on voice / video_note */
    duration?: number
    /** Peaks 0..100, present on voice */
    waveform?: number[]
    /** Present on video_note */
    shape?:   VideoNoteShape
    /** Upload-time VT verdict, or null if pending or out of scope. The SDK does not subscribe to live updates */
    virusTotalVerdict: 'clean' | 'suspicious' | 'malware' | string | null
    /** Resolves with plaintext bytes, rejects on 404 / 410 / tamper */
    download:  () => Promise<Buffer>
}


/** One item inside a gallery. Files have a download(), contact and location items just carry metadata */
export type IncomingGalleryItem =
    | { kind: 'file'; attachment: IncomingAttachment }
    | {
        kind: 'contact'
        userId: number
        username?:    string
        displayName?: string
        avatarUrl?:   string
        avatarUnicode?: string
    }
    | { kind: 'location'; lat: number; lng: number }


/** 2-10 items in one bubble. Caption (if any) is surfaced on IncomingMessage.text */
export interface IncomingGallery {
    items: IncomingGalleryItem[]
}
